CREATE TABLE terapeutas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    rol VARCHAR(40) NOT NULL,
    especialidad VARCHAR(160) NOT NULL,
    cedula_profesional VARCHAR(60) NOT NULL UNIQUE,
    telefono VARCHAR(30)
);

CREATE TABLE administrativos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    rol VARCHAR(40) NOT NULL,
    departamento VARCHAR(120) NOT NULL,
    puesto VARCHAR(120) NOT NULL
);

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(160) NOT NULL,
    celular VARCHAR(30),
    email VARCHAR(120),
    tipo_servicio VARCHAR(40) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    sexo VARCHAR(20) NOT NULL,
    edad INT,
    fecha_registro DATE NOT NULL,
    fecha_proxima_sesion DATE,
    terapeuta_id BIGINT,
    CONSTRAINT fk_paciente_terapeuta FOREIGN KEY (terapeuta_id) REFERENCES terapeutas (id)
);

CREATE TABLE sesiones_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    terapeuta_id BIGINT NOT NULL,
    numero_sesion INT NOT NULL,
    tipo_sesion VARCHAR(40) NOT NULL,
    fecha DATE NOT NULL,
    asistencia VARCHAR(20) NOT NULL,
    duracion_minutos INT,
    motivo_cancelacion VARCHAR(250),
    descripcion VARCHAR(2000) NOT NULL,
    observaciones VARCHAR(2000),
    CONSTRAINT fk_sesion_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT fk_sesion_terapeuta FOREIGN KEY (terapeuta_id) REFERENCES terapeutas (id)
);

CREATE INDEX idx_pacientes_terapeuta ON pacientes (terapeuta_id);
CREATE INDEX idx_sesiones_paciente ON sesiones_clinicas (paciente_id);
CREATE INDEX idx_sesiones_terapeuta ON sesiones_clinicas (terapeuta_id);

INSERT INTO terapeutas (nombre, correo, password, rol, especialidad, cedula_profesional, telefono) VALUES
('Dra. Ana Martínez', '@correo1.com', 'password1', 'TERAPEUTA', 'Psicología Clínica', 'CED123456', '555-1234'),
