CREATE TABLE sesiones_clinicas_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    snapshot TEXT NOT NULL,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificado_por BIGINT,
    comentario VARCHAR(255)
);
CREATE INDEX idx_sesion_history_sesion ON sesiones_clinicas_history(sesion_id);
